name: lint check
on:
  push:
    branches:
      - feature/master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo running on branch ${GITHUB_REF##*/}
      - uses: actions/checkout@v2 # 用于检测action是否正确
      - uses: actions/setup-node@v3
      - run: npm i -g pnpm
      - name: install packages
        run: pnpm i
      - run: pnpm lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    environment:
      name: deploy_env
    outputs:
      tags: ${{steps.meta.outputs.tags}}
    steps:
      - name: log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: tpjt/legion # 镜像名称

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{steps.meta.outputs.tags}} #上一步所拿到的tags，默认是分支名字
          labels: ${{steps.meta.outputs.labels}} # 上一步所拿到的labels, github 中的相关数据

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: pull docker and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }} #云服务器的ip
          username: ${{ secrets.SERVER_USERNAME }} #云服务器的用户名
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            ref=${{ github.ref_name }}
            tag=${ref/\//\-}
            docker login --username=${{secrets.DOCKER_USERNAME}}  --password=${{secrets.DOCKER_PASSWORD}}
            if [ -n "$(docker ps -a -q  --filter ancestor=tpjt/legion:$tag)" ]; then
              docker rm $(docker stop $(docker ps -a -q  --filter ancestor=tpjt/legion:$tag))
            fi
            docker rmi tpjt/legion:$tag
            docker pull tpjt/legion:$tag
            docker run -dp 8080:80 tpjt/legion:$tag
